apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels: 
    {{- if .Values.deployment.labels }}
{{ toYaml .Values.deployment.labels | indent 4 }}
    {{- end }}
    app: {{ .Chart.Name }}
    tags.datadoghq.com/env: {{ .Values.datadog.labels.env }}
    tags.datadoghq.com/service: {{ .Chart.Name }}
    tags.datadoghq.com/version: {{ .Chart.Version }}
    admission.datadoghq.com/enabled: "true"
  annotations: 
    {{- if .Values.deployment.annotations }}
{{ tpl (toYaml .Values.deployment.annotations) . | indent 8 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels: 
        {{- if .Values.containers.labels }}
{{ toYaml .Values.containers.labels | indent 8 }}
        {{- end }}
        app: {{ .Chart.Name }}
        tags.datadoghq.com/env: {{ .Values.datadog.labels.env }}
        tags.datadoghq.com/service: {{ .Chart.Name }}
        tags.datadoghq.com/version: {{ .Chart.Version }}
      annotations:
        {{- if .Values.containers.annotations }}
{{ toYaml .Values.containers.annotations | indent 8 }}
        {{- end }}
        admission.datadoghq.com/python-lib.version: v1.20.1
    spec:
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets.secret }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        {{- with .Values.containers.secrets }}
        envFrom:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        env:
        - name: DD_PROFILING_ENABLED
          value: "true"
        - name: DD_LOGS_INJECTION
          value: "true"
